"""
actions/file_generator.py — Universal Multi-Format Document Authoring Engine for JARVIS Mark 58
Empowers JARVIS to generate all kinds of files on demand:
- Word Documents (.docx) with formatted headings, styled tables, and bullet points.
- PowerPoint Presentations (.pptx) with modern slide layouts, cards, and speaker notes.
- PDF Documents (.pdf) with clean typography, tables, and revision cheat sheets using ReportLab.
- Excel Spreadsheets (.xlsx, .csv) with headers, formulas, and auto-sized columns using OpenPyXL.
- Code & Text Files (.py, .md, .txt, .html, .tex, .json).
"""

import os
import sys
import json
import subprocess
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Optional

BASE_DIR = Path(__file__).resolve().parent.parent

def _get_output_dir(target_location: str = "desktop") -> Path:
    """Resolves target folder, default to Desktop."""
    loc = (target_location or "desktop").lower().strip()
    if loc in ("desktop", "desk"):
        cand = Path.home() / "OneDrive" / "Desktop"
        if cand.exists(): return cand
        return Path.home() / "Desktop"
    elif loc in ("downloads", "down"):
        cand = Path.home() / "OneDrive" / "Downloads"
        if cand.exists(): return cand
        return Path.home() / "Downloads"
    elif loc in ("documents", "docs"):
        cand = Path.home() / "OneDrive" / "Documents"
        if cand.exists(): return cand
        return Path.home() / "Documents"
    
    p = Path(target_location).expanduser()
    if p.exists() and p.is_dir():
        return p
    return Path.home() / "Desktop"


def create_word_document(
    filename: str,
    title: str,
    sections: List[Dict[str, Any]],
    output_dir: Optional[Path] = None,
    open_after: bool = True
) -> str:
    """
    Creates a styled Word (.docx) document.
    sections: list of dicts:
      {"heading": "Title", "content": "Paragraph text", "bullets": ["...", "..."], "table": [["col1", "col2"], ...]}
    """
    try:
        import docx
        from docx.shared import Inches, Pt, RGBColor
        from docx.enum.text import WD_ALIGN_PARAGRAPH
        from docx.oxml import OxmlElement
        from docx.oxml.ns import qn

        if not filename.endswith(".docx"):
            filename += ".docx"

        out_dir = output_dir or _get_output_dir()
        file_path = out_dir / filename

        doc = docx.Document()

        # Page margins
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(0.8)
            section.right_margin = Inches(0.8)

        # Document Title
        p_title = doc.add_paragraph()
        run_title = p_title.add_run(title)
        run_title.font.name = "Calibri"
        run_title.font.size = Pt(24)
        run_title.font.bold = True
        run_title.font.color.rgb = RGBColor(14, 116, 144)  # Stark Cyan/Teal
        p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Subtitle / Timestamp
        p_sub = doc.add_paragraph()
        run_sub = p_sub.add_run(f"Generated by JARVIS Mark 58 • {datetime.now().strftime('%B %d, %Y')}")
        run_sub.font.name = "Calibri"
        run_sub.font.size = Pt(10)
        run_sub.font.italic = True
        run_sub.font.color.rgb = RGBColor(100, 116, 139)
        p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        doc.add_paragraph()

        for sec in sections:
            h_text = sec.get("heading")
            if h_text:
                h = doc.add_heading(h_text, level=sec.get("level", 1))
                for run in h.runs:
                    run.font.name = "Calibri"
                    run.font.color.rgb = RGBColor(30, 41, 59)

            content = sec.get("content")
            if content:
                p = doc.add_paragraph()
                r = p.add_run(content)
                r.font.name = "Calibri"
                r.font.size = Pt(11)

            bullets = sec.get("bullets", [])
            for b in bullets:
                p = doc.add_paragraph(style='List Bullet')
                r = p.add_run(b)
                r.font.name = "Calibri"
                r.font.size = Pt(11)

            table_data = sec.get("table")
            if table_data and isinstance(table_data, list) and len(table_data) > 0:
                rows = len(table_data)
                cols = len(table_data[0])
                table = doc.add_table(rows=rows, cols=cols)
                table.style = 'Table Grid'
                for r_idx, row in enumerate(table_data):
                    for c_idx, val in enumerate(row):
                        cell = table.cell(r_idx, c_idx)
                        cell.text = str(val)
                        if r_idx == 0:
                            for p in cell.paragraphs:
                                for run in p.runs:
                                    run.font.bold = True
                doc.add_paragraph()

        doc.save(str(file_path))

        if open_after:
            try:
                os.startfile(str(file_path))
            except Exception:
                pass

        return f"Successfully created Word document: '{file_path.name}' at {file_path.parent}"

    except Exception as e:
        return f"Failed to generate Word document: {e}"


def create_presentation(
    filename: str,
    title: str,
    subtitle: str,
    slides_data: List[Dict[str, Any]],
    output_dir: Optional[Path] = None,
    open_after: bool = True
) -> str:
    """
    Creates a modern PowerPoint (.pptx) presentation.
    slides_data: list of dicts:
      {"title": "Slide Title", "bullets": ["Point 1", "Point 2"], "notes": "Speaker notes"}
    """
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
        from pptx.dml.color import RGBColor
        from pptx.enum.text import PP_ALIGN

        if not filename.endswith(".pptx"):
            filename += ".pptx"

        out_dir = output_dir or _get_output_dir()
        file_path = out_dir / filename

        prs = Presentation()
        # Set 16:9 widescreen
        prs.slide_width = Inches(13.333)
        prs.slide_height = Inches(7.5)

        # Slide 1: Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        t_box = slide.shapes.title
        s_box = slide.placeholders[1]

        t_box.text = title
        s_box.text = f"{subtitle}\nGenerated by J.A.R.V.I.S. Mark 58"

        # Content Slides
        bullet_slide_layout = prs.slide_layouts[1]
        for s_info in slides_data:
            s_title = s_info.get("title", "Key Point")
            bullets = s_info.get("bullets", [])
            notes_text = s_info.get("notes", "")

            c_slide = prs.slides.add_slide(bullet_slide_layout)
            c_slide.shapes.title.text = s_title
            body_shape = c_slide.placeholders[1]
            tf = body_shape.text_frame
            tf.word_wrap = True

            for idx, b_text in enumerate(bullets):
                p = tf.add_paragraph() if idx > 0 else tf.paragraphs[0]
                p.text = b_text
                p.level = 0
                p.font.size = Pt(20)

            if notes_text:
                notes_slide = c_slide.notes_slide
                notes_slide.notes_text_frame.text = notes_text

        prs.save(str(file_path))

        if open_after:
            try:
                os.startfile(str(file_path))
            except Exception:
                pass

        return f"Successfully generated PowerPoint Presentation: '{file_path.name}' ({len(slides_data) + 1} slides) at {file_path.parent}"

    except Exception as e:
        return f"Failed to generate PowerPoint presentation: {e}"


def create_pdf_document(
    filename: str,
    title: str,
    sections: List[Dict[str, Any]],
    output_dir: Optional[Path] = None,
    open_after: bool = True
) -> str:
    """
    Creates a formatted PDF document using ReportLab.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib import colors
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

        if not filename.endswith(".pdf"):
            filename += ".pdf"

        out_dir = output_dir or _get_output_dir()
        file_path = out_dir / filename

        doc = SimpleDocTemplate(
            str(file_path),
            pagesize=letter,
            rightMargin=54, leftMargin=54,
            topMargin=54, bottomMargin=54
        )

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#0e7490'),
            alignment=1, # Center
            spaceAfter=14
        )
        heading_style = ParagraphStyle(
            'SecHeading',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#1e293b'),
            spaceBefore=12,
            spaceAfter=6
        )
        body_style = ParagraphStyle(
            'BodyTextCustom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            spaceAfter=6
        )
        bullet_style = ParagraphStyle(
            'BulletCustom',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=10,
            leading=14,
            leftIndent=15,
            firstLineIndent=-10,
            textColor=colors.HexColor('#1e293b'),
            spaceAfter=4
        )

        story = []
        story.append(Paragraph(title, title_style))
        story.append(Paragraph(f"<i>Prepared by J.A.R.V.I.S. Mark 58 • {datetime.now().strftime('%B %d, %Y')}</i>", body_style))
        story.append(Spacer(1, 16))

        for sec in sections:
            h = sec.get("heading")
            if h:
                story.append(Paragraph(h, heading_style))

            content = sec.get("content")
            if content:
                story.append(Paragraph(content, body_style))

            bullets = sec.get("bullets", [])
            for b in bullets:
                story.append(Paragraph(f"&bull; {b}", bullet_style))

            tbl_data = sec.get("table")
            if tbl_data and isinstance(tbl_data, list) and len(tbl_data) > 0:
                t = Table(tbl_data)
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#f1f5f9')),
                    ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#0f172a')),
                    ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                    ('FONTSIZE', (0,0), (-1,-1), 9),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 5),
                    ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cbd5e1')),
                ]))
                story.append(Spacer(1, 6))
                story.append(t)
                story.append(Spacer(1, 8))

        doc.build(story)

        if open_after:
            try:
                os.startfile(str(file_path))
            except Exception:
                pass

        return f"Successfully generated PDF Document: '{file_path.name}' at {file_path.parent}"

    except Exception as e:
        return f"Failed to generate PDF document: {e}"


def create_excel_sheet(
    filename: str,
    title: str,
    columns: List[str],
    rows: List[List[Any]],
    output_dir: Optional[Path] = None,
    open_after: bool = True
) -> str:
    """
    Creates an Excel spreadsheet (.xlsx) using OpenPyXL.
    """
    try:
        from openpyxl import Workbook
        from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
        from openpyxl.utils import get_column_letter

        if not filename.endswith(".xlsx"):
            filename += ".xlsx"

        out_dir = output_dir or _get_output_dir()
        file_path = out_dir / filename

        wb = Workbook()
        ws = wb.active
        ws.title = title[:30] if title else "Sheet1"

        # Headers
        header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="0E7490", end_color="0E7490", fill_type="solid")
        border_thin = Border(
            left=Side(style='thin', color='CBD5E1'),
            right=Side(style='thin', color='CBD5E1'),
            top=Side(style='thin', color='CBD5E1'),
            bottom=Side(style='thin', color='CBD5E1')
        )

        ws.append(columns)
        for col_idx in range(1, len(columns) + 1):
            cell = ws.cell(row=1, column=col_idx)
            cell.font = header_font
            cell.fill = header_fill
            cell.alignment = Alignment(horizontal="center", vertical="center")

        # Rows
        for r_data in rows:
            ws.append(r_data)

        # Style data cells and auto-adjust widths
        for row in ws.iter_rows(min_row=2, max_row=len(rows)+1, min_col=1, max_col=len(columns)):
            for cell in row:
                cell.font = Font(name="Calibri", size=10)
                cell.border = border_thin

        for col in ws.columns:
            max_len = max(len(str(cell.value or '')) for cell in col)
            col_letter = get_column_letter(col[0].column)
            ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

        wb.save(str(file_path))

        if open_after:
            try:
                os.startfile(str(file_path))
            except Exception:
                pass

        return f"Successfully generated Excel Spreadsheet: '{file_path.name}' ({len(rows)} rows) at {file_path.parent}"

    except Exception as e:
        return f"Failed to generate Excel spreadsheet: {e}"


def universal_file_creator(parameters: dict, player=None) -> str:
    """
    Main tool handler for creating any file requested by the user.
    parameters:
      file_type: 'docx' | 'pptx' | 'pdf' | 'xlsx' | 'code' | 'text' | 'markdown'
      filename: Target filename (e.g. 'Financial_Markets_Revision.docx')
      title: Document/Presentation Title
      content: Raw content string or JSON-structured outline
      target_location: 'desktop' | 'downloads' | 'documents' | custom path
      open_after: bool (default True)
    """
    params = parameters or {}
    f_type = (params.get("file_type") or "docx").lower().strip()
    filename = (params.get("filename") or f"JARVIS_Document_{datetime.now().strftime('%H%M%S')}").strip()
    title = params.get("title") or "Academic Document"
    raw_content = params.get("content") or ""
    location = params.get("target_location", "desktop")
    open_after = params.get("open_after", True)
    out_dir = _get_output_dir(location)

    if player and hasattr(player, "write_log"):
        player.write_log(f"FILE ENGINE: Creating {f_type.upper()} file '{filename}'...")

    # 1. Word Document
    if f_type in ("docx", "word", "doc"):
        sections = []
        if isinstance(raw_content, list):
            sections = raw_content
        elif isinstance(raw_content, dict):
            sections = raw_content.get("sections", [])
        else:
            # Parse text into paragraphs & bullet blocks
            lines = raw_content.splitlines()
            cur_sec = {"heading": title, "content": "", "bullets": []}
            for line in lines:
                l_s = line.strip()
                if l_s.startswith("# "):
                    if cur_sec["content"] or cur_sec["bullets"]: sections.append(cur_sec)
                    cur_sec = {"heading": l_s[2:], "content": "", "bullets": []}
                elif l_s.startswith("## "):
                    if cur_sec["content"] or cur_sec["bullets"]: sections.append(cur_sec)
                    cur_sec = {"heading": l_s[3:], "level": 2, "content": "", "bullets": []}
                elif l_s.startswith("- ") or l_s.startswith("* "):
                    cur_sec["bullets"].append(l_s[2:])
                else:
                    cur_sec["content"] += (" " + l_s) if cur_sec["content"] else l_s
            sections.append(cur_sec)

        return create_word_document(filename, title, sections, output_dir=out_dir, open_after=open_after)

    # 2. PowerPoint Presentation
    elif f_type in ("pptx", "powerpoint", "presentation", "slides"):
        subtitle = params.get("subtitle", "Comprehensive Briefing")
        slides_data = []
        if isinstance(raw_content, list):
            slides_data = raw_content
        else:
            # Simple splitter by '---' or headers
            blocks = raw_content.split("---") if "---" in raw_content else raw_content.split("## ")
            for b in blocks:
                b_lines = [ln.strip() for ln in b.splitlines() if ln.strip()]
                if not b_lines: continue
                s_title = b_lines[0].lstrip("# ").strip()
                bullets = [ln.lstrip("-* ").strip() for ln in b_lines[1:] if ln.startswith(("-", "*", "•"))]
                if not bullets and len(b_lines) > 1:
                    bullets = b_lines[1:5]
                slides_data.append({"title": s_title, "bullets": bullets})

        if not slides_data:
            slides_data = [{"title": "Overview", "bullets": [raw_content[:200]]}]

        return create_presentation(filename, title, subtitle, slides_data, output_dir=out_dir, open_after=open_after)

    # 3. PDF Document
    elif f_type in ("pdf", "cram_sheet", "cheat_sheet"):
        sections = [{"heading": "Summary", "content": raw_content, "bullets": []}]
        if isinstance(raw_content, list):
            sections = raw_content
        return create_pdf_document(filename, title, sections, output_dir=out_dir, open_after=open_after)

    # 4. Excel Spreadsheet
    elif f_type in ("xlsx", "excel", "spreadsheet", "csv"):
        columns = params.get("columns") or ["Item", "Category", "Status", "Notes"]
        rows = params.get("rows") or [["Example 1", "Academics", "Completed", "Logged via JARVIS"]]
        return create_excel_sheet(filename, title, columns, rows, output_dir=out_dir, open_after=open_after)

    # 5. Code, Markdown or Plain Text
    else:
        ext_map = {"code": ".py", "python": ".py", "markdown": ".md", "md": ".md", "text": ".txt", "txt": ".txt", "html": ".html", "tex": ".tex", "json": ".json"}
        ext = ext_map.get(f_type, ".txt")
        if not filename.endswith(ext):
            filename += ext
        target_path = out_dir / filename
        target_path.write_text(raw_content, encoding="utf-8")
        if open_after:
            try:
                os.startfile(str(target_path))
            except Exception:
                pass
        return f"Successfully generated file: '{target_path.name}' at {target_path.parent}"
